name = "remix-cloudflare-workers"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "aichat-db"
database_id = "fb016ee8-12a7-4e20-a4e9-abb858163830"
